language: cpp
compiler:
  - gcc
before_install:
  - 'ci/before_install.sh'
before_script: cmake .
script:
  - make
  - sudo ldconfig --verbose # So the test executeables can detect libtinyxml2
  - make test
after_failure:
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
