// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define DART_ROOT_PATH "/home/jason/DRCDev/dart_refactoring/"
#define DART_DATA_PATH "/home/jason/DRCDev/dart_refactoring/data/"

#endif // ifndef UTILS_PATHS_H
